server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservice
    username: postgres
    password: 27092001

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HotelService

eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
          defaultZone: http://localhost:8761/eureka/
