server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microusers
    username: root
    password: 1910128
    driver-class-name: com.mysql.cj.jdbc.Driver # Use the correct driver class name


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true



