server:
  port: 8081

spring:
  application:
    name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/microusers
    username: root
    password: 1910128
    driver-class-name: com.mysql.cj.jdbc.Driver # Use the correct driver class name


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



  config:
    import: optional:configserver:http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-77471036.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaau5hj8tZNue0g95d7
            client-secret: DmUN3wuMJ87Kxs2jUT87Fcw9JDM0zPrUEcm9fpQhKKIIl0E8gwtdHzu5rlKxcH9L

        provider:
          okta:
            issuer-uri: https://dev-77471036.okta.com/oauth2/default


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 3s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s

#OKTA configuration for USER-SERVICE
okta:
  oauth2:
    issuer: https://dev-77471036.okta.com/oauth2/default
    audience: api://default
